### ISSUE TITLE
The "using PlotlyJS" execution does not finish

### ISSUE THREAD

**Issue by tsumanuma** [JuliaPlots/PlotlyJS.jl#476] opened 2023-11-14 14:53 UTC
Sorry for my bad English, I am Japanese.

The "using PlotlyJS" execution does not finish.
Sometimes restarting the PC after a while can make it work.
But after running the plot a few times, it stops working again.
I'd be glad for your advice. Thank you.

OS: Windows11
Julia: v1.9.3
IJulia: v1.24.2
Plotly: v0.4.1
PlotlyJS: v0.18.11
Plots: v1.39.0
Editor: Visual Studio Code
![image](https://github.com/JuliaPlots/PlotlyJS.jl/assets/82442540/a7250631-e6b5-4876-bfe1-2ffeddfb9981)

**Comment by jd-foster** [comment] 2023-11-15 13:21
Thanks for reporting.
This seems like a duplicate of #473

**Comment by tsumanuma** [comment] 2023-11-16 14:29
Thank you for your reply.
Would changing the version work?
Downgrading julia to 1.9.0 or PlotlyJS to 0.18.10 does not work.

**Closed** 2023-11-25 14:23 UTC
