### ISSUE TITLE
plotly-latest.min.js from artifact not working

### ISSUE THREAD

**Issue by dralletje** [JuliaPlots/PlotlyJS.jl#369] opened 2021-03-17 17:23 UTC
**Describe the bug**
When rendering a plotlyJS plot in html, it will fetch `plotly-latest.min.js`, which has nonsensical content (see image)
This is also what I see when I download and expand [the artifact](https://github.com/thomasjm/PlotlyJS.jl/releases/download/v0.14/plotly.js-artifacts-1.57.1.tar.gz) manually.
It might be that it is GZIP'ed, and the server that serves it is supposed to figure that out?
I'm implementing WebIO in Pluto.jl, didn't test it on Jupyter or anything, but my code worked perfectly before yesterdays release (and switching to v0.14.0 now solves it)

![image](https://user-images.githubusercontent.com/767261/111508648-37e5bf80-874c-11eb-976d-ad4e7499286a.png)
(This image is more huge than I intended it to be)

**`versioninfo()`**
```
Julia Version 1.6.0-rc1
Commit a58bdd9010 (2021-02-06 15:49 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_PATH = /usr/local/julia
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_VERSION = 1.6.0-rc1
  JULIA_REVISE_WORKER_ONLY = 1
```

**`pkg"status"`**
```
[97c1335a] JSExpr v0.5.2
[f0f68f2c] PlotlyJS v0.14.1
[0f1e0344] WebIO v0.8.15
```

**Comment by kobussch** [comment] 2021-04-10 21:52
This comment can maybe point somebody in the right direction and provide a temporary workaround for Windows 10 Home users who cannot get PlotlyJS 0.14.1 working at the moment. I did a fresh install of literally everything after re-installing Windows, but then ran into this blank Electron window issue. If I go back one version to 0.14.0, I get errors when Kaleido is called up, so I am stuck in the middle. I tried out the pull request of #372 but it did not work for me (both Julia 1.5.x and Julia 1.6.0). While playing around with #372 in shared development mode, I stumbled on a temporary workaround. If you revert back to 0.14.0 using git tools in the development repo, followed by a rebuild of PlotlyJS, everything works again. This is a temporary fix though, because it is not advisable to keep the package in development mode indefinitely. For those not familiar with development mode, switch to pkg mode in the REPL and enter ?develop. I can add that on my company laptop with Windows 10 Pro, I also get the blank window problem, but here I had success by just stipulating 0.14.0 when I added PlotlyJS in pkg mode. The develop trick was not necessary in Windows 10 Pro

**Comment by dralletje** [comment] 2021-04-10 22:52
For me it always works if I do
```julia
] add PlotlyJS@0.14.0
```

**Comment by andreasnoack** [comment] 2021-04-11 18:31
I have a problem that might be similar to this one. With 0.14.1, the plots don't show up in the Electron window. I'm able to save the plots to files, though.

**Comment by sglyon** [comment] 2021-04-12 14:46
Thanks everyone for reporting 

I’m going to be unable to work on a fix for this for a week or two. I’d be thankful if anyone was able to make a pass at this and would gladly review a pull request. 

Thanks!

**Comment by kobussch** [comment] 2021-04-13 13:51
My previous comment on the pull request  #372 not working was a bit vague. I think the pull request might actually work. From the error messages it looks like the artifact url given in the suggested artifacts.toml is simply not accessible to me. This url is probably something that only the author of the package can set up successfully. The suggested generate_artifacts file looks to be in better shape than the old one. I will try and build my a local artifact using this file and see how it goes from there. This can save Spencer a bit of testing time on the Windows platform.

**Comment by kobussch** [comment] 2021-04-13 19:41
I can confirm that #372 works as advertised when used to build a local artifact on a Windows 10 Home PC and probably on all other platforms as well. The artifact url is still broken and must be fixed. Three small issues to point out:
1.  A KDiff check shows every single file changed. That probably means that line-end coding is different. 
2. `Artifacts` is now available directly from `Main` and also from inside `Pkg`. This causes a conflict warning. It should probably stay that way because may users will still be on Julia 1.5.x
3.  In addition to the artifact generation fix, #372 also modified the way that schema information is extracted. I am not familiar with this part of the process, but I can confirm that the generated html is still the same except for one spelling correction.

So thumbs-up from me for #372 and thanks to the contributor. If you want to use this as a temporary fix, be warned that the
process of linking to a local artifact as generated from a floating pull request is non-trivial for a casual user, so here is an abbreviated list of steps. Let me know if there is a simpler way:
- from inside REPL, update PlotlyJS to the latest version(0.14.1)
- put PlotlyJS in develop mode
- enter `using PlotlyJS , Artifacts`
- call `Pkg.status("PlotlyJS")` to find the development folder and `cd` to this folder from within the REPL and don't exit.
- download the #372 suggested code to a different folder (unzip if needed). 
- copy everything except the .git and similar stuff over to the development folder
- in REPL, enter `include("deps/generate_artifacts.jl")` . This will build the artifact content from external sources and pack it into a tarball in the development folder
- in REPL enter `bind_artifact!(artifacts_toml, "plotly-artifacts", plotlyartifacts_hash, download_info=[
("file:"*joinpath(dirname(artifacts_toml),"plotly-artifacts.tar.gz"), tarball_hash)], force=true)` . This will modify the Artifacts.toml file to refer to the local tarball.
- build PlotlyJS
- restart REPL
- do functional test (`using PlotlyJS;plot(rand(10))` -you know the drill)

Keep an eye on the github repo from time to time and when a new version is released, do `Pkg.free("PlotlyJS") to revert back to the mainstream.

**Comment by sglyon** [comment] 2021-04-20 12:59
Hi @kobussch thank you for taking a look and writing a great report.

Let's see what we can do to get #372 merged!

**Comment by el-oso** [comment] 2021-05-05 11:36
Has this fix been merged? I think that I have the same problem.

**Comment by ndgnuh** [comment] 2021-05-29 07:45
Everyone with this problem can just download plotly.min.js from [their cdn](https://cdn.plot.ly/plotly-latest.min.js?_ga=2.121197320.1499553278.1622184868-1200682804.1619515858), replace the plotly.min.js file the one downloaded in the artifact folder, and it will be just fine.

**Comment by dhanak** [comment] 2021-06-04 08:00
> For me it always works if I do
> 
> ```julia
> ] add PlotlyJS@0.14.0
> ```

Sadly, this also stopped working with Julia 1.6 (fresh install or at least fresh depot), because this Julia version builds the dependencies in a separate scratchspace, and PlotlyJS@0.14.0 relies on having an empty `build.log` file in its `deps` folder after a successful build. If it is not there, it won't load. A workaround is to touch it manually, but I'm really not happy about either this or the workaround for 0.14.1.

**Closed** 2021-06-18 15:32 UTC
