### ISSUE TITLE
Package installation failure on fresh Julia 1.4.2 install

### ISSUE THREAD

**Issue by isaacsas** [JuliaPlots/PlotlyJS.jl#330] opened 2020-05-31 16:35 UTC
```julia
(@v1.4) pkg> add PlotlyJS
  Resolving package versions...
  Installed IniFile ───────────────────── v0.5.0
  Installed Mustache ──────────────────── v1.0.3
  Installed AssetRegistry ─────────────── v0.1.0
  Installed Pidfile ───────────────────── v1.1.0
  Installed Hiccup ────────────────────── v0.2.2
  Installed Lazy ──────────────────────── v0.15.0
  Installed HTTP ──────────────────────── v0.8.15
  Installed PlotlyBase ────────────────── v0.3.1
  Installed PlotlyJS ──────────────────── v0.13.1
  Installed DataValueInterfaces ───────── v1.0.0
  Installed Widgets ───────────────────── v0.6.2
  Installed TableTraits ───────────────── v1.0.0
  Installed Observables ───────────────── v0.3.1
  Installed FunctionalCollections ─────── v0.5.0
  Installed WebIO ─────────────────────── v0.8.14
  Installed BinDeps ───────────────────── v1.0.1
  Installed IteratorInterfaceExtensions ─ v1.0.0
  Installed Compat ────────────────────── v3.10.0
  Installed JSExpr ────────────────────── v0.5.2
  Installed URIParser ─────────────────── v0.4.1
  Installed Mux ───────────────────────── v0.7.0
  Installed Tables ────────────────────── v1.0.4
  Installed WebSockets ────────────────── v1.5.2
  Installed DocStringExtensions ───────── v0.8.1
  Installed Blink ─────────────────────── v0.12.3
   Updating `~/.julia/environments/v1.4/Project.toml`
  [f0f68f2c] + PlotlyJS v0.13.1
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [bf4720bc] + AssetRegistry v0.1.0
  [9e28174c] + BinDeps v1.0.1
  [ad839575] + Blink v0.12.3
  [34da2185] + Compat v3.10.0
  [e2d170a0] + DataValueInterfaces v1.0.0
  [ffbed154] + DocStringExtensions v0.8.1
  [de31a74c] + FunctionalCollections v0.5.0
  [cd3eb016] + HTTP v0.8.15
  [9fb69e20] + Hiccup v0.2.2
  [83e8ac13] + IniFile v0.5.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [97c1335a] + JSExpr v0.5.2
  [50d2b5c4] + Lazy v0.15.0
  [ffc61752] + Mustache v1.0.3
  [a975b10e] + Mux v0.7.0
  [510215fc] + Observables v0.3.1
  [fa939f87] + Pidfile v1.1.0
  [a03496cd] + PlotlyBase v0.3.1
  [f0f68f2c] + PlotlyJS v0.13.1
  [3783bdb8] + TableTraits v1.0.0
  [bd369af6] + Tables v1.0.4
  [30578b45] + URIParser v0.4.1
  [0f1e0344] + WebIO v0.8.14
  [104b5d7c] + WebSockets v1.5.2
  [cc8bc4a8] + Widgets v0.6.2
  [1a1011a3] + SharedArrays 
   Building WebIO ───→ `~/.julia/packages/WebIO/nTMDV/deps/build.log`
   Building Blink ───→ `~/.julia/packages/Blink/u1xcH/deps/build.log`
   Building PlotlyJS → `~/.julia/packages/PlotlyJS/AhkM5/deps/build.log`
┌ Error: Error building `PlotlyJS`: 
│ ┌ Error: Download failed: curl: (60) SSL certificate problem: certificate has expired
│ └ @ Base download.jl:43
│ ERROR: LoadError: Failed to download plotschema.json from https://api.plot.ly/v2/plot-schema?sha1. You may use your web-browser to download it from https://api.plot.ly/v2/plot-schema?sha1 and place it in /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] datadown(::String, ::String, ::String) at /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps/build.jl:15
│  [3] top-level scope at /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps/build.jl:20
│  [4] include(::String) at ./client.jl:439
│  [5] top-level scope at none:5
│ in expression starting at /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps/build.jl:20
│ caused by [exception 1]
│ failed process: Process(`/usr/bin/curl -s -S -g -L -f -o /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps/plotschema.json 'https://api.plot.ly/v2/plot-schema?sha1'`, ProcessExited(60)) [60]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] download_curl(::String, ::String, ::String) at ./download.jl:44
│  [3] download(::String, ::String) at ./download.jl:62
│  [4] datadown(::String, ::String, ::String) at /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps/build.jl:10
│  [5] top-level scope at /Users/isaacsas/.julia/packages/PlotlyJS/AhkM5/deps/build.jl:20
│  [6] include(::String) at ./client.jl:439
│  [7] top-level scope at none:5
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:899
```

**Version info**
```julia
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

```julia
(@v1.4) pkg> st
Status `~/.julia/environments/v1.4/Project.toml`
  [7073ff75] IJulia v1.21.2
  [f0f68f2c] PlotlyJS v0.13.1
  [91a5bcdd] Plots v1.3.6
  [438e738f] PyCall v1.91.4
  [d330b81b] PyPlot v2.9.0
  [295af30f] Revise v2.7.0
```

**Comment by sglyon** [comment] 2020-06-01 17:24
Hmm I can't reproduce this. Is there any chance you are behind a firewall or have other network settings that could block the request?

Another possibility is that there was a temporary issue with plotly's SSL certs that has been resolved in the time between when you tried and when I did just now? Could you try again and report back?

Thanks

**Comment by harryscholes** [comment] 2020-06-02 12:26
I already have PlotlyJS.jl installed in an environment and get the following when I do

```julia
using Plots; plotlyjs()
```

```
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
[ Info: Precompiling PlotlyJS [f0f68f2c-4968-5e81-91da-67840de0976a]
WARNING: redefining constant pages
WARNING: redefining constant server
WARNING: redefining constant port
WARNING: redefining constant known_mimetypes
WARNING: redefining constant singleton_instance
WARNING: redefining constant routing_callback
WARNING: redefining constant webio_server_config
┌ Warning: Warnings were generated during the last build of PlotlyJS:  please check the build log at /Users/harry/.julia/packages/PlotlyJS/AhkM5/deps/build.log
└ @ PlotlyJS ~/.julia/packages/PlotlyJS/AhkM5/src/PlotlyJS.jl:85
```

The build log contains

```
┌ Error: Download failed: curl: (60) SSL certificate problem: certificate has expired
└ @ Base download.jl:43
┌ Warning: Failed to update plotschema.json, but you already have it. Things might continue to work, but if you would like to make sure you have the latest version of plotschema.json, use may use your web-browser to download it from https://api.plot.ly/v2/plot-schema?sha1 and place it in /Users/harry/.julia/packages/PlotlyJS/AhkM5/deps.
└ @ Main ~/.julia/packages/PlotlyJS/AhkM5/deps/build.jl:13
```

**Comment by harryscholes** [comment] 2020-06-02 12:39
Temporary fix that works for me:

```
] add PlotlyJS@0.13.0
```

**Comment by isaacsas** [comment] 2020-06-02 15:10
I'm not behind a firewall or have anything I'm aware that could block the request. (I'm working from home, and have never had such issues before.)

I'll investigate more and report back when I have a chance. I ultimately got everything working by manually downloading plotschema.json using a web browser as described in the error message.

**Comment by sglyon** [comment] 2020-09-03 16:19
Is this still a problem?

I can't replicate right now so I will close. If it is a problem for anyone, please feel free to comment or re-open.

**Closed by sglyon** 2020-09-03 16:19 UTC
Labels: help wanted

**Comment by isaacsas** [comment] 2020-09-03 16:29
Yes, seems fixed. My apologies for forgetting to update you! Thanks for the help before!

**Comment by sglyon** [comment] 2020-09-03 21:33
no problem, glad it is working!
