### ISSUE TITLE
Pre-compilation does not finish with version 0.18.11

### ISSUE THREAD

**Issue by SupplyChef** [JuliaPlots/PlotlyJS.jl#477] opened 2023-12-09 18:49 UTC
I am developing a package that uses PlotlyJS. When I upgraded to version 0.18.11 the pre-compilation would not complete and would get stopped on github after 6 hours. Reverting to version 0.18.10 makes the pre-compilation work again. 
 
Please provide the following:

Julia Version 1.9.4
Commit 8e5136fa29 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
  JULIA_NUM_THREADS = 1

  [31c24e10] Distributions v0.25.104
  [86223c79] Graphs v1.9.0
  [f0f68f2c] PlotlyJS v0.18.11
  [8a0b78ce] SupplyChainModeling v0.1.2
  [ade2ca70] Dates
  [cf7118a7] UUIDs

**Comment by beorostica** [comment] 2023-12-29 18:22
This appears to be a duplicate of https://github.com/JuliaPlots/PlotlyJS.jl/issues/473. The issue is also addressed in https://discourse.julialang.org/t/plotlyjs-0-18-11-hangs-when-trying-using-but-only-the-first-time/105636/5.

**Comment by NicolasRiel** [comment] 2024-02-19 19:23
I am not sure this is the same problem

I am having similar issues on Windows 10-11 and also Ubuntu 22

When adding my package on these machines it gets stuck during the pre-compilation of DashBasePlotlyJSExt (hangs forever).

I was working just fine before Julia 1.10

**Comment by BeastyBlacksmith** [comment] 2024-02-20 08:28
That is most likely https://github.com/JuliaPlots/PlotlyKaleido.jl/issues/13

**Comment by BeastyBlacksmith** [comment] 2024-02-23 14:43
Please try 0.18.13

**Comment by NicolasRiel** [comment] 2024-02-24 09:25
Hi, so version 0.18.13 does help with the pre-compilation on Windows, that can be completed now.

However, when "using my_package" it now loads forever (on Windows only). I have to cancel the "using my_package" and relaunch it several times before it is able to actually load the package. This is especially a problem for the CI as because of this it still fails on Windows!

Hope this helps, and thanks for the support

Nicolas

**Comment by disberd** [comment] 2024-03-05 17:40
This should be solved now. See the related comment in https://github.com/JuliaPlots/PlotlyJS.jl/issues/473#issuecomment-1979300463 for more details

**Closed by disberd** 2024-03-05 17:40 UTC
