### ISSUE TITLE
Errors on importing PlotlyJS after fresh install on nightly Julia

### ISSUE THREAD

**Issue by robsmith11** [JuliaPlots/PlotlyJS.jl#363] opened 2021-01-26 08:17 UTC
If I call import/using a second time, there is no error and I can use PlotlyJS fine.

```
(@v1.7) pkg> status
      Status `~/.julia/environments/v1.7/Project.toml`
  [f0f68f2c] PlotlyJS v0.14.0

julia> versioninfo()
Julia Version 1.7.0-DEV.383
Commit bf15b706e9* (2021-01-26 04:39 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

```julia> using PlotlyJS
ERROR: InitError: SystemError: opening file "/home/me/.julia/packages/PlotlyJS/m2Lzd/deps/build.log": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:168
  [2] #systemerror#66
    @ ./error.jl:167 [inlined]
  [3] systemerror
    @ ./error.jl:167 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:282 [inlined]
  [6] open(f::Base.var"#354#355"{String}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:328
  [7] open
    @ ./io.jl:328 [inlined]
  [8] read
    @ ./io.jl:435 [inlined]
  [9] __init__()
    @ PlotlyJS ~/.julia/packages/PlotlyJS/m2Lzd/src/PlotlyJS.jl:65
 [10] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:670
 [11] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:756
 [12] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:994
 [13] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:910
 [14] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:897
during initialization of module PlotlyJS
```

**Comment by sglyon** [comment] 2021-01-26 17:42
Thanks @robsmith11

I'm not working on nightly right now, so I don't think I'll be able to contribute a fix. 

That being said, I'm happy to review a PR if someone who does work on nightly is willing to tackle this one

**Comment by jonas-kr** [comment] 2021-02-07 21:23
I am encountering the same issue on 1.6.0-rc1. However, the generated plots are not displayed in the Blink window. 
@robsmith11 Are you able to reproduce this issue on the nightly build as well?
Anyway, I will try to dig deeper to ensure compatibility with the new release as soon as possible :)

**Comment by robsmith11** [comment] 2021-02-08 01:46
Thanks for looking into it more, @jonas-kr.  I've always just exported the plot to a html file and viewed it in Firefox, so I've never tried using Blink, but it's likely broken here too.

**Comment by sglyon** [comment] 2021-02-08 21:05
@jonas-kr I don't know much about this scratch spaces api

Is this something you could help us integrate here?

**Comment by jonas-kr** [comment] 2021-02-09 06:25
Honestly, I do not know anything about this api, yet. However, I will try to look into this.

**Comment by ericphanson** [comment] 2021-03-14 22:10
It looks to me like this was fixed in https://github.com/JuliaPlots/PlotlyJS.jl/commit/c4418ccc2537d1954913af351da9fbd71a55175b, there just hasn't been a release since then

**Comment by jonas-kr** [comment] 2021-03-17 08:53
@ericphanson Thanks a lot for this hint, this commit does provide a workaround for the issue. Actually, building the package on an 1.6.0-rc3 build creates an (in my case empty) build.log file in a subdirectory of .julia/scratchspaces. Hence, it seems like the only thing that remains to be fixed is the path of this build.log file. I will try to resolve this issue asap.

**Comment by sglyon** [comment] 2021-03-17 13:56
I did just release a fresh version of plotlyJS in response to @ericphanson comment (thanks for the reminder!)

Hopefully things work on latest release of this package

**Closed** 2023-02-28 07:36 UTC
