### ISSUE TITLE
Plots don't display in Jupyter with WebIO v0.8.1

### ISSUE THREAD

**Issue by halleysfifthinc** [JuliaPlots/PlotlyJS.jl#278] opened 2019-04-15 22:18 UTC
Upon updating WebIO to v0.8.1 from v0.7.0, plots no longer display/mount in Jupyter. This is reproducible (for me) in a clean environment with only IJulia and PlotlyJS added.

With `] st` of
```
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [7073ff75] IJulia v1.18.1
  [f0f68f2c] PlotlyJS v0.12.3
  [0f1e0344] WebIO v0.8.1
```

running `using IJulia` and `plot(scatter(;y=rand(50)))` doesn't show any plot. (In the Firefox developer console, running the plot cell produces a "Jupyter WebIO extension detected, not mounting.")

After pinning Webio to v0.7.0, running those same commands in jupyter does produce a plot. (And I can see several XHR requests for JS files being made which don't happen with WebIO at v0.8.1.)

I also tried this with on PlotlyJS master with WebIO v0.8.1 which didn't work (no plot).

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by sglyon** [comment] 2019-04-16 00:35
Thanks @halleysfifthinc for letting us know and for doing some homework on it.

Very helpful.

perhaps @travigd or @shashi know why recent WebIO changes would have broken things?

**Comment by travigd** [comment] 2019-04-16 01:17
Few diagnostic questions.
* Is this using Jupyter notebook or Jupyter lab?
* How are you launching Jupyter (_e.g._ `jupyter notebook` command or from within Julia running `using IJulia; notebook()` or something else)? Have you tried restarting?
* Can you produce the output of `jupyter --data-dir`? That directory (for me it's `/home/travigd/.local/share/jupyter`) should contain an `nbextensions` directory and that directory should contain a `webio` directory.
```sh
$ ls $(jupyter --data-dir)/nbextensions/webio
main.js
```

Thanks!

**Comment by halleysfifthinc** [comment] 2019-04-16 15:29
This is in Jupyter notebook, launched from terminal with `jupyter notebook`. Do you mean restarting my whole computer or Jupyter? I restarted Jupyter in between the environment changes.

I have the same contents of the webio nbextension as above:
```
$ ls $(jupyter --data-dir)/nbextensions/webio
main.js
```

**Comment by travigd** [comment] 2019-04-16 15:32
Hmmm... and there are no errors in the console? Can you (in the browser console) run `localStorage.debug = "*"` and refresh and see if there's any other output there? It should look something like this.

![Screenshot from 2019-04-16 11-31-56](https://user-images.githubusercontent.com/773453/56223196-4e081400-603b-11e9-8900-844cbf275780.png)

**Comment by halleysfifthinc** [comment] 2019-04-16 16:25
I don't see anything like that. This is all I see, but this is before anything is run:
```
WebIO:jupyter-notebook Registering WebIO node MIME type (application/vnd.webio.node+json). +0ms main.js:1:6001
WebIO:jupyter-notebook OutputArea display order: +1ms 
Array(11) [ "application/vnd.webio.node+json", "application/javascript", "text/html", "text/markdown", "text/latex", "image/svg+xml", "image/png", "image/jpeg", "image/gif", "application/pdf", … ]
main.js:1:6001
WebIO:jupyter-notebook Rerendering all WebIO cells. +1ms main.js:1:6001
```

**Comment by DhruvaSambrani** [comment] 2019-04-19 11:07
https://github.com/sglyon/PlotlyJS.jl/issues/255#issuecomment-484853552

**Comment by sglyon** [comment] 2019-04-19 11:42
Hi @halleysfifthinc Are you running this in jupyterlab or the notebook?

if you are running in jupyterlab try installing the jupyterlab plotly extension as noted in the just published update to the [readme](https://github.com/sglyon/PlotlyJS.jl#jupyterlab) of this repo. 

That still doesn't quite fix the WebIO in jupyter problem (so you won't be able to do cool WebIO dependent things like update a chart was already displayed or assign julia callbacks to plot events), but at least you'll be able to see your plots

**Comment by shashi** [comment] 2019-04-19 19:26
Hi @halleysfifthinc

I know this should have run on its own, but could you try again after running `]build WebIO` and restarting the Jupyter server?

**Comment by halleysfifthinc** [comment] 2019-04-19 20:47
@sglyon, this is in Jupyter notebook, not jupyterlab. For the moment, everything is working fine for me with WebIO pinned at v0.7.0; plots show up fine with that version.

@shashi I said in the first comment that I switched between the two mentioned environments (the difference between the two being WebIO v0.7.0 and WebIO v0.8.1) and built everything (WebIO included) before starting the Jupyter server.

**Comment by JobJob** [comment] 2019-05-03 18:53
I have the same problem as the OP (in jupyter notebook) in v0.8.1, and working in v0.7.0. 

@travigd @shashi try find me on the Julia slack if you want to more interactively debug this.

**Comment by DhruvaSambrani** [comment] 2019-06-01 12:10
This was supposed to be solved after WebIO updated to 0.8.2. Look at [https://github.com/JuliaGizmos/WebIO.jl/pull/286](this). But PlotlyJS 0.12.4 has a dependency of WebIO 0.8.1, and this needs to be updated.

**Comment by sglyon** [comment] 2019-06-01 14:49
@DhruvaSambrani in the [Project.toml for PlotlyJS 0.12.4](https://github.com/sglyon/PlotlyJS.jl/blob/v0.12.4/Project.toml) it looks like the requirement is WebIO version at least 0.8.0. I don't see a 0.8.1 anywhere, could I be missing it?

If not, then I suppose an `up` command from pkg mode should get the latest WebIO and we can test if the latest fixes PlotlyJS?

**Comment by DhruvaSambrani** [comment] 2019-06-02 08:21
Yes sorry, it's not a problem with PlotlyJS but instead with WebIO. They haven't released the 0.8.2 and 0.8.3 packages publicly yet. I'm opening an issue there. Let's see how it goes!

**Comment by DhruvaSambrani** [comment] 2019-06-07 17:26
I've updated WebIO to the latest version (v0.8.4), 
I see

>  Warning: Accessing scope.id is deprecated; use scopeid(scope) instead.
>  caller = ip:0x0
>  @ Core :-1

and 

>WebIO not detected

with no plot. Are we absolutely sure its a WebIO issue? Because other WebIO objects are rendering perfectly

**Comment by sglyon** [comment] 2019-06-07 17:44
might be an issue with how we use WebIO here. @travigd any idea?

**Comment by travigd** [comment] 2019-06-07 20:03
The WebIO not detected method implies that nothing WebIO related is getting rendered.

**Comment by travigd** [comment] 2019-06-07 20:25
If you get `WebIO not detected`, please...
* Update to latest WebIO (especially important for Windows - there was a fix about installing the extensions to the wrong place on Windows due to not correctly expanding path macros like `%APPDATA%`)
* Rebuild `WebIO`
* Check output of `jupyter nbextension list` and see whether or not WebIO is listed there (and whether or not there's an error)

**Comment by travigd** [comment] 2019-06-07 20:34
Ah - there is an issue here.

There needs to be a `display` method for
```
Base.show(::IO, ::WebIO.WEBIO_NODE_MIME, ::SyncPlot)
```

I thought we had some logic to try to do this automatically in WebIO (basically define a method for `show(::IO, ::WEBIO_NODE_MIME, ::T)` that then checks if a relevant `WebIO.render(::T)` method is defined) but I'm not sure. @sglyon can we chat in Slack?

**Comment by DhruvaSambrani** [comment] 2019-06-08 04:44
> If you get `WebIO not detected`, please...
> 
> * Update to latest WebIO (especially important for Windows - there was a fix about installing the extensions to the wrong place on Windows due to not correctly expanding path macros like `%APPDATA%`)
> * Rebuild `WebIO`
> * Check output of `jupyter nbextension list` and see whether or not WebIO is listed there (and whether or not there's an error)

> 
> Known nbextensions:
>   config dir: C:\Users\Dhruva Sambrani\.jupyter\nbconfig
>     notebook section
>       codefolding/main enabled
>       - Validating: ok
>       printview/main disabled
>       skill/main enabled
>       - Validating: ok
>       hinterland/hinterland enabled
>       - Validating: ok
>       scratchpad/main enabled
>       - Validating: ok
>       autosavetime/main enabled
>       - Validating: ok
>       skip-traceback/main disabled
>       **webio/main enabled
>       - Validating: ok**
>       splitcell/splitcell enabled
>       - Validating: ok
>       collapsible_headings/main enabled
>       - Validating: ok
>       execute_time/ExecuteTime enabled
>       - Validating: ok
>       toc2/main enabled
>       - Validating: ok
>       notify/notify enabled
>       - Validating: ok
>     edit section
>       codefolding/edit enabled
>       - Validating: ok
>   config dir: c:\program files\python37\etc\jupyter\nbconfig
>     notebook section
>       jupyter-js-widgets/extension enabled
>       - Validating: ok
>   config dir: C:\ProgramData\jupyter\nbconfig
>     notebook section
>       nbextensions_configurator/config_menu/main enabled
>       - Validating: problems found:
>         - require?  X nbextensions_configurator/config_menu/main
>       contrib_nbextensions_help_item/main enabled
>       - Validating: ok
>     tree section
>       nbextensions_configurator/tree_tab/main enabled
>       - Validating: problems found:
>         - require?  X nbextensions_configurator/tree_tab/main

**Comment by jingpengw** [comment] 2019-06-19 20:20
thanks for working on this issue!

I tried to switch to @travigd 's WebIO branch
https://github.com/JuliaGizmos/WebIO.jl/tree/td/add-register-renderable-macro

Unfortunately, I still can not see any plot, I got this message in the browser console:
```
Jupyter WebIO nbextension detected; not loading ad-hoc.
VM1369:3 Jupyter WebIO extension detected, not mounting.
```

**Comment by jingpengw** [comment] 2019-06-19 20:21
just find that my issue is here:
https://github.com/sglyon/PlotlyJS.jl/issues/255

this is probably not related.

**Comment by ghuba** [comment] 2019-06-27 22:26
I am having a similar issue. No plot shows up in my Jupyter notebooks. Any advice on what to do?

`[f0f68f2c] PlotlyJS v0.12.4`

```
jupyter nbextension list
Known nbextensions:
  config dir: /Users/.../.jupyter/nbconfig
    notebook section
      webio/main  enabled 
      - Validating: OK
  config dir: /Users/.../anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

```
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Command to start notebook:

`using IJulia; notebook(dir=".")`

In the Chrome developer console:

![image](https://user-images.githubusercontent.com/4511360/60304826-645e0600-98ef-11e9-9569-604bae496881.png)

Screenshot of notebook:

![image](https://user-images.githubusercontent.com/4511360/60304867-82c40180-98ef-11e9-928f-24874449e9c3.png)

**Comment by sglyon** [comment] 2019-06-28 19:06
#285 addresses this problem and has been merged. Would people here be willing to test out the latest master?

I could not reproduce the issue, so having another test would be helpful (Thanks @travigd  for the fix and @DhruvaSambrani  for testing already)!

Either when I get another positive report or a day or two has passed I'll release a new version, whichever happens first

Thanks!

**Comment by ghuba** [comment] 2019-06-28 22:00
Let me give it a try!

**Comment by ghuba** [comment] 2019-06-28 22:10
Happy to report this is working now! Problem fixed. Here are some screenshots. There are still a couple of minor warnings but it looks benign.

![image](https://user-images.githubusercontent.com/4511360/60373772-4b6c5800-99b6-11e9-94a8-132c80a04e66.png)


```
┌ Info: Recompiling stale cache file /Users/.../.julia/compiled/v1.1/PlotlyJS/1r9Ld.ji for PlotlyJS [f0f68f2c-4968-5e81-91da-67840de0976a]
└ @ Base loading.jl:1184
WARNING: could not import Base.quit into AtomShell
```

Chrome Console messages

![image](https://user-images.githubusercontent.com/4511360/60373908-c33a8280-99b6-11e9-806a-f70c11161f48.png)


Julia Version 1.1.1
macOS (x86_64-apple-darwin15.6.0)

**Comment by sglyon** [comment] 2019-06-28 22:13
Thanks!

**Comment by cstjean** [comment] 2019-07-10 18:03
The example works for me too, but not for my more complex app :disappointed:. The console  shows this:

```
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:5
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later... menubar.js:304
accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects contructors at creation time main.js:208
Loaded moment locale en-ca bidi.js:19
load_extensions 
Arguments { 0: "jupyter-js-widgets/extension", 1: "webio/main", … }
utils.js:60
Session: kernel_created (857d86c7-b019-4b2d-8760-e1fb7a16e5b8) session.js:54
Starting WebSockets: ws://magneto:8897/api/kernels/165d228e-6e6b-42fc-9333-0f34d5017287 kernel.js:459
WebIO is registering SystemJS window global. main.js:1:39743
Loading extension: webio/main utils.js:37
Loading extension: jupyter-js-widgets/extension utils.js:37
setTimeout executed 0 main.js:1:125191
Kernel: kernel_connected (165d228e-6e6b-42fc-9333-0f34d5017287) kernel.js:103
Kernel: kernel_ready (165d228e-6e6b-42fc-9333-0f34d5017287) kernel.js:103
WebIO detected Jupyter notebook environment. main.min.js:14:17
Jupyter WebIO nbextension detected; not loading ad-hoc. main.min.js:23:21
WebIO detected Jupyter notebook environment. main.min.js:14:17
Jupyter WebIO nbextension detected; not loading ad-hoc. main.min.js:23:21
Jupyter WebIO extension detected, not mounting.
main.min.js:2:17
WebIO detected Jupyter notebook environment. main.min.js:14:17
Jupyter WebIO nbextension detected; not loading ad-hoc. main.min.js:23:21
Jupyter WebIO extension detected, not mounting.
main.min.js:2:17
Source map error: request failed with status 404
Resource URL: http://magneto:8897/static/components/proptypes/index.js?v=c40890eb04df9811fcc4d47e53a29604
Source Map URL: index.js.map

Source map error: request failed with status 404
Resource URL: http://magneto:8897/static/components/preact/index.js?v=00a2fac73c670ce39ac53d26640eb542
Source Map URL: preact.min.js.map

Source map error: request failed with status 404
Resource URL: http://magneto:8897/static/components/preact-compat/index.js?v=f865e990e65ad27e3a2601d8adb48db1
Source Map URL: preact-compat.min.js.map
```

The last three errors seem unrelated? When I paste the URLs in the browser it works fine.

**Comment by sglyon** [comment] 2019-07-10 21:18
Grr I thought we had solved this one. 

Is there any way you can create a minimal example from your more complex app that we could look at?

It’s hard to diagnose without seeing code

**Comment by DhruvaSambrani** [comment] 2019-07-11 09:54
@cstjean are you using it with Plots? That still doesn't work

**Comment by cstjean** [comment] 2019-07-11 10:58
No, I'm using it directly, but it's fairly involved. I'll do a MWE when I get the time, which might be in September...

**Comment by gurvesh** [comment] 2019-07-22 16:37
Hi - I still get the same error. This is a fresh install of Julia. I've tried upgrading Jupyterlab, building Webio - still nothing shows.

![Screenshot from 2019-07-22 22-05-54](https://user-images.githubusercontent.com/8342402/61648432-0c87a480-accd-11e9-9a65-3f3a0bb2da3e.png)

**Comment by gurvesh** [comment] 2019-07-22 16:49
Actually - it works in Jupyter notebook, but not in Jupyterlab. Also, as Dhruva said - it works only if used directly, but not via Plots.

**Comment by Masacroso** [comment] 2019-07-26 12:45
> 
> 
> Actually - it works in Jupyter notebook, but not in Jupyterlab. Also, as Dhruva said - it works only if used directly, but not via Plots.

it doesn't work in classical jupyter notebook either. I tried now in a jupyter notebook this code

```
using PlotlyJS
function area1()
    trace1 = scatter(;x=1:4, y=[0, 2, 3, 5], fill="tozeroy")
    trace2 = scatter(;x=1:4, y=[3, 5, 1, 7], fill="tonexty")
    plot([trace1, trace2])
end
```

But when I executed `area1()` it just show an empty cell. Context: Julia 1.1.1, IJulia 1.18.1, PlotlyJS 0.12.4 and WebIO 0.8.5. In windows 10 64 bits.

**Comment by DhruvaSambrani** [comment] 2019-07-26 14:29
> But when I executed `area1()` it just show an empty cell. Context: Julia 1.1.1, IJulia 1.18.1, PlotlyJS 0.12.4 and WebIO 0.8.5. In windows 10 64 bits.
@Masacroso you need to update to PlotlyJS 0.12.4

**Comment by Masacroso** [comment] 2019-07-26 16:46
> 
> 
> > But when I executed `area1()` it just show an empty cell. Context: Julia 1.1.1, IJulia 1.18.1, PlotlyJS 0.12.4 and WebIO 0.8.5. In windows 10 64 bits.
> 
> @Masacroso you need to update to PlotlyJS 0.12.5

For some reason I cannot update PlotlyJS, Im writing `] update plotlyJS` in the REPL but it doesn't update.

**Comment by xiaodaigh** [comment] 2020-10-06 02:47
getting the same issues now ungrade doesn't work

**Comment by mananbordia** [comment] 2021-04-02 18:24
Executed plot in Jupyter Notebook but gives blank output.

**Comment by empet** [comment] 2021-04-02 18:52
What Julia and PlotlyJS.jl version are you working with?

**Comment by mananbordia** [comment] 2021-04-02 19:08
PlotlyJS => v"0.14.1"
 Julia => v"1.4.2"

**Comment by empet** [comment] 2021-04-02 19:30
With Julia 1.6.0 and the same PlotlyJS version it works. I installed the last Julia version a few days before, and it worked with 1.5.2.   too.

Have you plotted with configuration  before or this is the first trial?

**Comment by mananbordia** [comment] 2021-04-02 22:08
I have installed Julia 1.6.0 and reinstalled PlotlyJS but still face the same issue.
<img width="1075" alt="Screenshot 2021-04-03 at 3 33 47 AM" src="https://user-images.githubusercontent.com/45929094/113457640-eddc2980-942d-11eb-8186-cfaff770b541.png">

**Comment by diegozea** [comment] 2021-09-13 14:37
Same issue on Julia 1.6.2, with IJulia v1.23.2, WebIO v0.8.15, and PlotlyJS v0.18.7

![Screenshot from 2021-09-13 16-32-57](https://user-images.githubusercontent.com/2822757/133103176-1f2dfe01-e11a-40e0-be2b-7207d0aaed73.png)

![Screenshot from 2021-09-13 16-33-34](https://user-images.githubusercontent.com/2822757/133103188-73cc4dac-1695-4732-a0f3-dd52653573ff.png)


The webio extension is installed:
```
shell> /home/diego/.local/bin/jupyter nbextension list
Known nbextensions:
  config dir: /home/diego/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      webio-jupyter-notebook  enabled 
      - Validating: OK
```

**Comment by travigd** [comment] 2021-09-14 15:41
@diegozea Can you try updating to the latest WebIO and installing the new Jupyter extension? https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/

**Comment by diegozea** [comment] 2021-09-15 22:46
I have updated it, and it works! Thanks! :)

**Closed** 2022-12-09 15:24 UTC
